name: Android CI


on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run:  |
        mkdir test
        cd test
        git clone --recurse-submodules https://git.zx2c4.com/wireguard-android
        cd wireguard-android
        git checkout 1.0.20220516
        ./gradlew assemble
        cd ui/build/outputs/apk
        echo "APP=$PWD" >> $GITHUB_ENV
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: WireGuard_release
        path: ${{ env.APP }}
    
